# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: component_manifest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63omponent_manifest.proto\"\x97\x03\n\nmanifest_t\x12\x18\n\x10manifest_version\x18\x01 \x01(\x05\x12\x12\n\nec_version\x18\x02 \x01(\t\x12/\n\x0e\x63omponent_list\x18\r \x03(\x0b\x32\x17.manifest_t.component_t\x1a\xa9\x02\n\x0b\x63omponent_t\x12\x16\n\x0e\x63omponent_type\x18\x03 \x01(\t\x12\x16\n\x0e\x63omponent_name\x18\x04 \x01(\t\x12*\n\x03i2c\x18\x07 \x01(\x0b\x32\x1d.manifest_t.component_t.i2c_t\x12,\n\x04usbc\x18\t \x01(\x0b\x32\x1e.manifest_t.component_t.usbc_t\x12,\n\x04ssfc\x18\x0c \x01(\x0b\x32\x1e.manifest_t.component_t.ssfc_t\x1a#\n\x05i2c_t\x12\x0c\n\x04port\x18\x05 \x01(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x06 \x01(\t\x1a\x16\n\x06usbc_t\x12\x0c\n\x04port\x18\x08 \x01(\x05\x1a%\n\x06ssfc_t\x12\x0c\n\x04mask\x18\n \x01(\t\x12\r\n\x05value\x18\x0b \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'component_manifest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MANIFEST_T']._serialized_start=29
  _globals['_MANIFEST_T']._serialized_end=436
  _globals['_MANIFEST_T_COMPONENT_T']._serialized_start=139
  _globals['_MANIFEST_T_COMPONENT_T']._serialized_end=436
  _globals['_MANIFEST_T_COMPONENT_T_I2C_T']._serialized_start=338
  _globals['_MANIFEST_T_COMPONENT_T_I2C_T']._serialized_end=373
  _globals['_MANIFEST_T_COMPONENT_T_USBC_T']._serialized_start=375
  _globals['_MANIFEST_T_COMPONENT_T_USBC_T']._serialized_end=397
  _globals['_MANIFEST_T_COMPONENT_T_SSFC_T']._serialized_start=399
  _globals['_MANIFEST_T_COMPONENT_T_SSFC_T']._serialized_end=436
# @@protoc_insertion_point(module_scope)
