# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Variant config
CONFIG_BOARD_ROACH=y

# placeholder, we don't have a real touchpad fw yet.
CONFIG_PLATFORM_EC_TOUCHPAD_VIRTUAL_SIZE=65536
CONFIG_PLATFORM_EC_TOUCHPAD_VIRTUAL_OFF=2147483648

CONFIG_PLATFORM_EC_TOUCHPAD_ELAN=y

CONFIG_PLATFORM_EC_ONE_WIRE_UART_KEYBOARD=n

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_LOG=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_USBD_HID_LOG_LEVEL_WRN=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y
CONFIG_USBD_HID_SUPPORT=y
CONFIG_USBD_HID_PRODUCT="Roach"
CONFIG_USBD_HID_PID=0x5068
CONFIG_USBD_HID_SN="0"
CONFIG_USBD_HID_KEYBOARD=y
CONFIG_USBD_HID_VIVALDI=y
CONFIG_USBD_HID_TOUCHPAD=y

CONFIG_PLATFORM_EC_USB_UPDATE=y
