/* Copyright 2013 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/**
 * @file
 * @brief Register map for the LPC family of chips
 *
 * This header file should only contain register definitions and
 * functionality that are common to all LPC chips.
 * Any chip/family specific macros must be placed in their family
 * specific registers file, which is conditionally included at the
 * end of this file.
 */

#ifndef __CROS_EC_REGISTERS_H
#define __CROS_EC_REGISTERS_H

#define UNIMPLEMENTED_GPIO_BANK 0

#define LPR_IRQ_I2C0 41
#define LPR_IRQ_TIM16B0 41
#define LPR_IRQ_TIM16B1 42
#define LPR_IRQ_TIM32B0 43
#define LPR_IRQ_TIM32B1 44
#define LPR_IRQ_SPI0 45
#define LPR_IRQ_UART 46
#define LPR_IRQ_USB 47
#define LPR_IRQ_USB_FIQ 48
#define LPR_IRQ_ADC 49
#define LPR_IRQ_WDT 50
#define LPR_IRQ_BOD 51
#define LPR_IRQ_PIO_3 53
#define LPR_IRQ_PIO_2 54
#define LPR_IRQ_PIO_1 55
#define LPR_IRQ_PIO_0 56
#define LPR_IRQ_SPI1 57
/* Parameter TIMER has the format: 16Bn or 32Bn. */
#define IRQ_TIM(TIMER) CONCAT2(LPR_IRQ_TIM, TIMER)


#define LPC_I2C_BASE 0x40000000
#define LPC_WDT_BASE 0x40004000
#define LPC_UART_BASE 0x40008000
#define LPC_TIM16B0_BASE 0x4000C000
#define LPC_TIM16B1_BASE 0x40010000
#define LPC_TIM32B0_BASE 0x40014000
#define LPC_TIM32B1_BASE 0x40018000
#define LPC_ADC_BASE 0x4001C000
#define LPC_USB_BASE 0x40020000
#define LPC_PMU_BASE 0x40038000
#define LPC_FLASH_BASE 0x4003C000
#define LPC_SPI0_BASE 0x40040000
#define LPC_IOCON_BASE 0x40044000
#define LPC_SYSCFG_BASE 0x40048000
#define LPC_SPI1_BASE 0x40058000
#define LPC_GPIO_BASE(BANK) (0x50000000 + 0x10000 * (BANK))
#define LPC_TIM_BASE(TIMER) CONCAT3(LPC_TIM, TIMER, _BASE)

/*
 * System configuration
 */

#define LPC_SYSCFG_SYSMEMREMAP REG32(LPC_SYSCFG_BASE + 0x000)
#define LPC_SYSCFG_PRESETCTRL REG32(LPC_SYSCFG_BASE + 0x004)
#define LPC_SYSCFG_SYSPLLCTRL REG32(LPC_SYSCFG_BASE + 0x008)
#define LPC_SYSCFG_SYSPLLSTAT REG32(LPC_SYSCFG_BASE + 0x00C)
#define LPC_SYSCFG_USBPLLCTRL REG32(LPC_SYSCFG_BASE + 0x010)
#define LPC_SYSCFG_USBPLLSTAT REG32(LPC_SYSCFG_BASE + 0x014)
#define LPC_SYSCFG_SYSOSCCTRL REG32(LPC_SYSCFG_BASE + 0x020)
#define LPC_SYSCFG_WDTOSCCTRL REG32(LPC_SYSCFG_BASE + 0x024)
#define LPC_SYSCFG_IRCCTRL REG32(LPC_SYSCFG_BASE + 0x028)
#define LPC_SYSCFG_RESSTAT REG32(LPC_SYSCFG_BASE + 0x030)
#define LPC_SYSCFG_SYSPLLCLKSEL REG32(LPC_SYSCFG_BASE + 0x040)
#define LPC_SYSCFG_SYSPLLCLKUEN REG32(LPC_SYSCFG_BASE + 0x044)
#define LPC_SYSCFG_USBPLLCLKSEL REG32(LPC_SYSCFG_BASE + 0x048)
#define LPC_SYSCFG_USBPLLCLKUEN REG32(LPC_SYSCFG_BASE + 0x04C)
#define LPC_SYSCFG_MAINCLKSEL REG32(LPC_SYSCFG_BASE + 0x070)
#define LPC_SYSCFG_MAINCLKUEN REG32(LPC_SYSCFG_BASE + 0x074)
#define LPC_SYSCFG_SYSAHBCLKDIV REG32(LPC_SYSCFG_BASE + 0x078)
#define LPC_SYSCFG_SYSAHBCLKCTRL REG32(LPC_SYSCFG_BASE + 0x080)
#define LPC_SYSCFG_UARTCLKDIV REG32(LPC_SYSCFG_BASE + 0x098)
#define LPC_SYSCFG_SPI1CLKDIV REG32(LPC_SYSCFG_BASE + 0x09C)
#define LPC_SYSCFG_TRACECLKDIV REG32(LPC_SYSCFG_BASE + 0x0AC)
#define LPC_SYSCFG_SYSTICKCLKDIV REG32(LPC_SYSCFG_BASE + 0x0B0)
#define LPC_SYSCFG_USBCLKSEL REG32(LPC_SYSCFG_BASE + 0x0C0)
#define LPC_SYSCFG_USBCLKUEN REG32(LPC_SYSCFG_BASE + 0x0C4)
#define LPC_SYSCFG_USBCLKDIV REG32(LPC_SYSCFG_BASE + 0x0C8)
#define LPC_SYSCFG_WDTCLKSEL REG32(LPC_SYSCFG_BASE + 0x0D0)
#define LPC_SYSCFG_WDTCLKUEN REG32(LPC_SYSCFG_BASE + 0x0D4)
#define LPC_SYSCFG_WDTCLKDIV REG32(LPC_SYSCFG_BASE + 0x0D8)
#define LPC_SYSCFG_CLKOUTCLKSEL REG32(LPC_SYSCFG_BASE + 0x0E0)
#define LPC_SYSCFG_CLKOUTCLKUEN REG32(LPC_SYSCFG_BASE + 0x0E4)
#define LPC_SYSCFG_CLKOUTCLKDIV REG32(LPC_SYSCFG_BASE + 0x0E8)
#define LPC_SYSCFG_PIOPORCAP0 REG32(LPC_SYSCFG_BASE + 0x100)
#define LPC_SYSCFG_PIOPORCAP1 REG32(LPC_SYSCFG_BASE + 0x104)
#define LPC_SYSCFG_BODCTRL REG32(LPC_SYSCFG_BASE + 0x150)
#define LPC_SYSCFG_SYSTCKCAL REG32(LPC_SYSCFG_BASE + 0x154)
#define LPC_SYSCFG_STARTAPRP0 REG32(LPC_SYSCFG_BASE + 0x200)
#define LPC_SYSCFG_STARTERP0 REG32(LPC_SYSCFG_BASE + 0x204)
#define LPC_SYSCFG_STARTRSRP0CLR REG32(LPC_SYSCFG_BASE + 0x208)
#define LPC_SYSCFG_STARTSRP0 REG32(LPC_SYSCFG_BASE + 0x20C)
#define LPC_SYSCFG_STARTAPRP1 REG32(LPC_SYSCFG_BASE + 0x210)
#define LPC_SYSCFG_STARTERP1 REG32(LPC_SYSCFG_BASE + 0x214)
#define LPC_SYSCFG_STARTRSRP1CLR REG32(LPC_SYSCFG_BASE + 0x218)
#define LPC_SYSCFG_STARTSRP1 REG32(LPC_SYSCFG_BASE + 0x21C)
#define LPC_SYSCFG_PDSLEEPCFG REG32(LPC_SYSCFG_BASE + 0x230)
#define LPC_SYSCFG_PDAWAKECFG REG32(LPC_SYSCFG_BASE + 0x234)
#define LPC_SYSCFG_PDRUNCFG REG32(LPC_SYSCFG_BASE + 0x238)
#define LPC_SYSCFG_DEVICE_ID REG32(LPC_SYSCFG_BASE + 0x3F4)

#define LPC_SYSCFG_PLLCTRL_MSEL_POS 0
#define LPC_SYSCFG_PLLCTRL_MSEL_MASK (0x1F << LPC_SYSCFG_PLLCTRL_MSEL_POS)
#define LPC_SYSCFG_PLLCTRL_PSEL_POS 5
#define LPC_SYSCFG_PLLCTRL_PSEL_MASK (0x3 << LPC_SYSCFG_PLLCTRL_PSEL_POS)
#define LPC_SYSCFG_PLLCTRL_PSEL_1 (0x0 << LPC_SYSCFG_PLLCTRL_PSEL_POS)
#define LPC_SYSCFG_PLLCTRL_PSEL_2 (0x1 << LPC_SYSCFG_PLLCTRL_PSEL_POS)
#define LPC_SYSCFG_PLLCTRL_PSEL_4 (0x2 << LPC_SYSCFG_PLLCTRL_PSEL_POS)
#define LPC_SYSCFG_PLLCTRL_PSEL_8 (0x3 << LPC_SYSCFG_PLLCTRL_PSEL_POS)
#define LPC_SYSCFG_PLLSTAT_LOCK BIT(0)

#define LPC_SYSCFG_SYSAHBCLKCTRL_SYS BIT(0)
#define LPC_SYSCFG_SYSAHBCLKCTRL_ROM BIT(1)
#define LPC_SYSCFG_SYSAHBCLKCTRL_RAM BIT(2)
#define LPC_SYSCFG_SYSAHBCLKCTRL_FLASHREG BIT(3)
#define LPC_SYSCFG_SYSAHBCLKCTRL_FLASHARRAY BIT(4)
#define LPC_SYSCFG_SYSAHBCLKCTRL_I2C BIT(5)
#define LPC_SYSCFG_SYSAHBCLKCTRL_GPIO BIT(6)
#define LPC_SYSCFG_SYSAHBCLKCTRL_CT16B0 BIT(7)
#define LPC_SYSCFG_SYSAHBCLKCTRL_CT12B1 BIT(8)
#define LPC_SYSCFG_SYSAHBCLKCTRL_CT32B0 BIT(9)
#define LPC_SYSCFG_SYSAHBCLKCTRL_CT32B1 BIT(10)
#define LPC_SYSCFG_SYSAHBCLKCTRL_SPI0 BIT(11)
#define LPC_SYSCFG_SYSAHBCLKCTRL_UART BIT(12)
#define LPC_SYSCFG_SYSAHBCLKCTRL_ADC BIT(13)
#define LPC_SYSCFG_SYSAHBCLKCTRL_USB_REG BIT(14)
#define LPC_SYSCFG_SYSAHBCLKCTRL_WDT BIT(15)
#define LPC_SYSCFG_SYSAHBCLKCTRL_IOCON BIT(16)
#define LPC_SYSCFG_SYSAHBCLKCTRL_SPI1 BIT(18)

#define LPC_SYSCFG_PDRUNCFG_IRCOUT_PD BIT(0)
#define LPC_SYSCFG_PDRUNCFG_IRC_PD BIT(1)
#define LPC_SYSCFG_PDRUNCFG_FLASH_PD BIT(2)
#define LPC_SYSCFG_PDRUNCFG_BOD_PD BIT(3)
#define LPC_SYSCFG_PDRUNCFG_ADC_PD BIT(4)
#define LPC_SYSCFG_PDRUNCFG_SYSOSC_PD BIT(5)
#define LPC_SYSCFG_PDRUNCFG_WDTOSC_PD BIT(6)
#define LPC_SYSCFG_PDRUNCFG_SYSPLL_PD BIT(7)
#define LPC_SYSCFG_PDRUNCFG_USBPLL_PD BIT(8)
#define LPC_SYSCFG_PDRUNCFG_USBPAD_PD BIT(10)

#define LPC_USB_DEV_INT_ST REG32(LPC_USB_BASE + 0x0000)
#define LPC_USB_DEV_INT_EN REG32(LPC_USB_BASE + 0x0004)
#define LPC_USB_DEV_INT_CLR REG32(LPC_USB_BASE + 0x0008)
#define LPC_USB_DEV_INT_SET REG32(LPC_USB_BASE + 0x000C)
#define LPC_USB_CMD_CODE REG32(LPC_USB_BASE + 0x0010)
#define LPC_USB_CMD_DATA REG32(LPC_USB_BASE + 0x0014)
#define LPC_USB_RX_DATA REG32(LPC_USB_BASE + 0x0018)
#define LPC_USB_TX_DATA REG32(LPC_USB_BASE + 0x001C)
#define LPC_USB_RX_PLEN REG32(LPC_USB_BASE + 0x0020)
#define LPC_USB_TX_PLEN REG32(LPC_USB_BASE + 0x0024)
#define LPC_USB_CTRL REG32(LPC_USB_BASE + 0x0028)
#define LPC_USB_DEV_FIQ_SEL REG32(LPC_USB_BASE + 0x002C)

#define LPC_USB_DEV_INT_FRAME BIT(0)
#define LPC_USB_DEV_INT_EP(N) BIT(1 + N)
#define LPC_USB_DEV_INT_DEV_STAT BIT(9)
#define LPC_USB_DEV_INT_CC_EMPTY BIT(10)
#define LPC_USB_DEV_INT_CD_FULL BIT(11)
#define LPC_USB_DEV_INT_RXENDPKT BIT(12)
#define LPC_USB_DEV_INT_TXENDPKT BIT(13)

/*
 * GPIO
 */

#define LPC_GPIO_DATA(BASE, MASK) REG32((BASE) + 4 * (MASK))
#define LPC_GPIO_DIR(BASE) REG32((BASE) + 0x8000)
#define LPC_GPIO_IS(BASE) REG32((BASE) + 0x8004)
#define LPC_GPIO_IBE(BASE) REG32((BASE) + 0x8008)
#define LPC_GPIO_IEV(BASE) REG32((BASE) + 0x800C)
#define LPC_GPIO_IE(BASE) REG32((BASE) + 0x8010)
#define LPC_GPIO_RIS(BASE) REG32((BASE) + 0x8014)
#define LPC_GPIO_MIS(BASE) REG32((BASE) + 0x8018)
#define LPC_GPIO_MIC(BASE) REG32((BASE) + 0x801C)

/*
 * IO pad cofiguration
 */ 
#define LPC_IOCON_FUNC_POS 0
#define LPC_IOCON_FUNC_MASK (0x7 << LPC_IOCON_FUNC_POS)
#define LPC_IOCON_MODE_POS 3
#define LPC_IOCON_MODE_MASK (0x3 << LPC_IOCON_MODE_POS)
#define LPC_IOCON_MODE_NOPULL (0x0 << LPC_IOCON_MODE_POS)
#define LPC_IOCON_MODE_PULLDOWN (0x1 << LPC_IOCON_MODE_POS)
#define LPC_IOCON_MODE_PULLUP (0x2 << LPC_IOCON_MODE_POS)
#define LPC_IOCON_MODE_REPEAT (0x3 << LPC_IOCON_MODE_POS)
#define LPC_IOCON_HYS_POS 5
#define LPC_IOCON_HYS BIT(LPC_IOCON_HYS_POS)
#define LPC_IOCON_OD_POS 5
#define LPC_IOCON_OD BIT(LPC_IOCON_OD_POS)

#define LPC_IOCON_PIO2_6 REG32(LPC_IOCON_BASE + 0x000)
#define LPC_IOCON_PIO2_0 REG32(LPC_IOCON_BASE + 0x008)
#define LPC_IOCON_RESET_PIO0_0 REG32(LPC_IOCON_BASE + 0x00C)
#define LPC_IOCON_PIO0_1 REG32(LPC_IOCON_BASE + 0x010)
#define LPC_IOCON_PIO1_8 REG32(LPC_IOCON_BASE + 0x014)
#define LPC_IOCON_PIO0_2 REG32(LPC_IOCON_BASE + 0x01C)
#define LPC_IOCON_PIO2_7 REG32(LPC_IOCON_BASE + 0x020)
#define LPC_IOCON_PIO2_8 REG32(LPC_IOCON_BASE + 0x024)
#define LPC_IOCON_PIO2_1 REG32(LPC_IOCON_BASE + 0x028)
#define LPC_IOCON_PIO0_3 REG32(LPC_IOCON_BASE + 0x02C)
#define LPC_IOCON_PIO0_4 REG32(LPC_IOCON_BASE + 0x030)
#define LPC_IOCON_PIO0_5 REG32(LPC_IOCON_BASE + 0x034)
#define LPC_IOCON_PIO1_9 REG32(LPC_IOCON_BASE + 0x038)
#define LPC_IOCON_PIO3_4 REG32(LPC_IOCON_BASE + 0x03C)
#define LPC_IOCON_PIO2_4 REG32(LPC_IOCON_BASE + 0x040)
#define LPC_IOCON_PIO2_5 REG32(LPC_IOCON_BASE + 0x044)
#define LPC_IOCON_PIO3_5 REG32(LPC_IOCON_BASE + 0x048)
#define LPC_IOCON_PIO0_6 REG32(LPC_IOCON_BASE + 0x04C)
#define LPC_IOCON_PIO0_7 REG32(LPC_IOCON_BASE + 0x050)
#define LPC_IOCON_PIO2_9 REG32(LPC_IOCON_BASE + 0x054)
#define LPC_IOCON_PIO2_10 REG32(LPC_IOCON_BASE + 0x058)
#define LPC_IOCON_PIO2_2 REG32(LPC_IOCON_BASE + 0x05C)
#define LPC_IOCON_PIO0_8 REG32(LPC_IOCON_BASE + 0x060)
#define LPC_IOCON_PIO0_9 REG32(LPC_IOCON_BASE + 0x064)
#define LPC_IOCON_SWCLK_PIO0_10 REG32(LPC_IOCON_BASE + 0x068)
#define LPC_IOCON_PIO1_10 REG32(LPC_IOCON_BASE + 0x06C)
#define LPC_IOCON_PIO2_11 REG32(LPC_IOCON_BASE + 0x070)
#define LPC_IOCON_R_PIO0_11 REG32(LPC_IOCON_BASE + 0x074)
#define LPC_IOCON_R_PIO1_0 REG32(LPC_IOCON_BASE + 0x078)
#define LPC_IOCON_R_PIO1_1 REG32(LPC_IOCON_BASE + 0x07C)
#define LPC_IOCON_R_PIO1_2 REG32(LPC_IOCON_BASE + 0x080)
#define LPC_IOCON_PIO3_0 REG32(LPC_IOCON_BASE + 0x084)
#define LPC_IOCON_PIO3_1 REG32(LPC_IOCON_BASE + 0x088)
#define LPC_IOCON_PIO2_3 REG32(LPC_IOCON_BASE + 0x08C)
#define LPC_IOCON_SWDIO_PIO1_3 REG32(LPC_IOCON_BASE + 0x090)
#define LPC_IOCON_PIO1_4 REG32(LPC_IOCON_BASE + 0x094)
#define LPC_IOCON_PIO1_11 REG32(LPC_IOCON_BASE + 0x098)
#define LPC_IOCON_PIO3_2 REG32(LPC_IOCON_BASE + 0x09C)
#define LPC_IOCON_PIO1_5 REG32(LPC_IOCON_BASE + 0x0A0)
#define LPC_IOCON_PIO1_6 REG32(LPC_IOCON_BASE + 0x0A4)
#define LPC_IOCON_PIO1_7 REG32(LPC_IOCON_BASE + 0x0A8)
#define LPC_IOCON_PIO3_3 REG32(LPC_IOCON_BASE + 0x0AC)

/*
 * Timers
 */
#define LPC_TMR_IR(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0000)
#define LPC_TMR_TCR(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0004)
#define LPC_TMR_TC(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0008)
#define LPC_TMR_PR(TIM) REG32(LPC_TIM_BASE(TIM) + 0x000C)
#define LPC_TMR_PC(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0010)
#define LPC_TMR_MCR(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0014)
#define LPC_TMR_MR0(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0018)
#define LPC_TMR_MR1(TIM) REG32(LPC_TIM_BASE(TIM) + 0x001C)
#define LPC_TMR_MR2(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0020)
#define LPC_TMR_MR3(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0024)
#define LPC_TMR_CCR(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0028)
#define LPC_TMR_CR0(TIM) REG32(LPC_TIM_BASE(TIM) + 0x002C)
#define LPC_TMR_EMR(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0030)
#define LPC_TMR_CTCR(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0034)
#define LPC_TMR_PWMCON(TIM) REG32(LPC_TIM_BASE(TIM) + 0x0038)

#define LPC_TMR_IR_MR0INT BIT(0)
#define LPC_TMR_IR_MR1INT BIT(1)
#define LPC_TMR_IR_MR2INT BIT(2)
#define LPC_TMR_IR_MR3INT BIT(3)
#define LPC_TMR_IR_CR0INT BIT(4)

#endif /* __CROS_EC_REGISTERS_H */
