/* Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef __POWER__H
#define __POWER__H

#include "usb_pd_config.h"


/*define*/
/*wait*/
#define POWER_ADC_WAIT_TIME      20000

/*Port A*/
#define POWER_A_CC1_VCONN        IT83XX_GPIO_GPCRC4
#define POWER_A_CC1_VCONN_PORT   IT83XX_GPIO_GPDRC
#define POWER_A_CC1_VCONN_PIN    BIT4
#define POWER_A_CC2_VCONN        IT83XX_GPIO_GPCRC6
#define POWER_A_CC2_VCONN_PORT   IT83XX_GPIO_GPDRC
#define POWER_A_CC2_VCONN_PIN    BIT6

#define POWER_A_VBUS_INPUT       IT83XX_GPIO_GPCRD0
#define POWER_A_VBUS_INPUT_PORT  IT83XX_GPIO_GPDRD
#define POWER_A_VBUS_INPUT_PIN   BIT0
#define POWER_A_VBUS_OUTPUT      IT83XX_GPIO_GPCRD1
#define POWER_A_VBUS_OUTPUT_PORT IT83XX_GPIO_GPDRD
#define POWER_A_VBUS_OUTPUT_PIN  BIT1
#define POWER_A_VBUS_DROP        IT83XX_GPIO_GPCRE5
#define POWER_A_VBUS_DROP_PORT   IT83XX_GPIO_GPDRE
#define POWER_A_VBUS_DROP_PIN    BIT5

#define POWER_A_ENABLE_CC1_VCONN()    \
		SET_MASK(POWER_A_CC1_VCONN_PORT, POWER_A_CC1_VCONN_PIN)
#define POWER_A_DISABLE_CC1_VCONN()   \
		CLEAR_MASK(POWER_A_CC1_VCONN_PORT, POWER_A_CC1_VCONN_PIN)
#define POWER_A_ENABLE_CC2_VCONN()    \
		SET_MASK(POWER_A_CC2_VCONN_PORT, POWER_A_CC2_VCONN_PIN)
#define POWER_A_DISABLE_CC2_VCONN()   \
		CLEAR_MASK(POWER_A_CC2_VCONN_PORT, POWER_A_CC2_VCONN_PIN)

#define POWER_A_ENABLE_VBUS_INPUT()   \
		SET_MASK(POWER_A_VBUS_INPUT_PORT, POWER_A_VBUS_INPUT_PIN)
#define POWER_A_DISABLE_VBUS_INPUT()  \
		CLEAR_MASK(POWER_A_VBUS_INPUT_PORT, POWER_A_VBUS_INPUT_PIN)
#define POWER_A_ENABLE_VBUS_OUTPUT()  \
		SET_MASK(POWER_A_VBUS_OUTPUT_PORT, POWER_A_VBUS_OUTPUT_PIN)
#define POWER_A_DISABLE_VBUS_OUTPUT() \
		CLEAR_MASK(POWER_A_VBUS_OUTPUT_PORT, POWER_A_VBUS_OUTPUT_PIN)
#define POWER_A_ENABLE_VBUS_DROP()   \
		SET_MASK(POWER_A_VBUS_DROP_PORT, POWER_A_VBUS_DROP_PIN)
#define POWER_A_DISABLE_VBUS_DROP()  \
		CLEAR_MASK(POWER_A_VBUS_DROP_PORT, POWER_A_VBUS_DROP_PIN)

#define POWER_A_IS_ENABLE_VBUS_INPUT()  \
		((IS_MASK_SET(POWER_A_VBUS_INPUT_PORT, POWER_A_VBUS_INPUT_PIN) \
		> 0) ? TRUE:FALSE)
#define POWER_A_IS_ENABLE_VBUS_OUTPUT() \
		((IS_MASK_SET(POWER_A_VBUS_OUTPUT_PORT \
		, POWER_A_VBUS_OUTPUT_PIN) > 0) ? TRUE:FALSE)

/*Port B*/
#define POWER_B_CC1_VCONN           IT83XX_GPIO_GPCRA2
#define POWER_B_CC1_VCONN_PORT      IT83XX_GPIO_GPDRA
#define POWER_B_CC1_VCONN_PIN       BIT2
#define POWER_B_CC2_VCONN           IT83XX_GPIO_GPCRA3
#define POWER_B_CC2_VCONN_PORT      IT83XX_GPIO_GPDRA
#define POWER_B_CC2_VCONN_PIN       BIT3

#define POWER_B_VBUS_INPUT		IT83XX_GPIO_GPCRA4
#define POWER_B_VBUS_INPUT_PORT		IT83XX_GPIO_GPDRA
#define POWER_B_VBUS_INPUT_PIN		BIT4
#define POWER_B_VBUS_OUTPUT		IT83XX_GPIO_GPCRA5
#define POWER_B_VBUS_OUTPUT_PORT	IT83XX_GPIO_GPDRA
#define POWER_B_VBUS_OUTPUT_PIN		BIT5
#define POWER_B_VBUS_DROP		IT83XX_GPIO_GPCRA6
#define POWER_B_VBUS_DROP_PORT		IT83XX_GPIO_GPDRA
#define POWER_B_VBUS_DROP_PIN		BIT6

#define POWER_B_ENABLE_CC1_VCONN()   \
		SET_MASK(POWER_B_CC1_VCONN_PORT, POWER_B_CC1_VCONN_PIN)
#define POWER_B_DISABLE_CC1_VCONN()  \
		CLEAR_MASK(POWER_B_CC1_VCONN_PORT, POWER_B_CC1_VCONN_PIN)
#define POWER_B_ENABLE_CC2_VCONN()  \
		SET_MASK(POWER_B_CC2_VCONN_PORT, POWER_B_CC2_VCONN_PIN)
#define POWER_B_DISABLE_CC2_VCONN() \
		CLEAR_MASK(POWER_B_CC2_VCONN_PORT, POWER_B_CC2_VCONN_PIN)

#define POWER_B_ENABLE_VBUS_INPUT() \
		SET_MASK(POWER_B_VBUS_INPUT_PORT, POWER_B_VBUS_INPUT_PIN)
#define POWER_B_DISABLE_VBUS_INPUT() \
		CLEAR_MASK(POWER_B_VBUS_INPUT_PORT, POWER_B_VBUS_INPUT_PIN)
#define POWER_B_ENABLE_VBUS_OUTPUT() \
		SET_MASK(POWER_B_VBUS_OUTPUT_PORT, POWER_B_VBUS_OUTPUT_PIN)
#define POWER_B_DISABLE_VBUS_OUTPUT() \
		CLEAR_MASK(POWER_B_VBUS_OUTPUT_PORT, POWER_B_VBUS_OUTPUT_PIN)
#define POWER_B_ENABLE_VBUS_DROP()   \
		SET_MASK(POWER_B_VBUS_DROP_PORT, POWER_B_VBUS_DROP_PIN)
#define POWER_B_DISABLE_VBUS_DROP()  \
		CLEAR_MASK(POWER_B_VBUS_DROP_PORT, POWER_B_VBUS_DROP_PIN)

#define POWER_B_IS_ENABLE_VBUS_INPUT()  \
		((IS_MASK_SET(POWER_B_VBUS_INPUT_PORT \
		, POWER_B_VBUS_INPUT_PIN) > 0) ? TRUE:FALSE)
#define POWER_B_IS_ENABLE_VBUS_OUTPUT() \
		((IS_MASK_SET(POWER_B_VBUS_OUTPUT_PORT \
		, POWER_B_VBUS_OUTPUT_PIN) > 0) ? TRUE:FALSE)


/*ADC*/
#define ADC0     IT83XX_GPIO_GPCRI0
#define ADC1     IT83XX_GPIO_GPCRI1
/*ADC save5V threadhold(5V is 219)*/
#define ADC_5V_THRES_H  5500
#define ADC_5V_THRES_L  4500
/*ADC safe0V threadhold(5V is 247)*/
#define ADC_0V_THRES    500

/* declaration of struct and enum */
enum {POWER_IN, POWER_OUT};


/*Public variable*/


/*Public function*/
void power_init(uint8_t u8Port);
void power_enable_vconn(uint8_t u8Port, uint32_t u32CcPin, uint8_t bIsEnable);
void power_enable_vbus(uint8_t u8Port, uint8_t bIsEnable);
void power_enable_drop(uint8_t u8Port, uint8_t bEnable);
uint8_t power_is_enable_vbus(uint8_t u8Port);
void power_set_volt(uint8_t u8Port, uint8_t u8Dir, uint32_t u32mv);
uint32_t power_get_m_volt(uint8_t u8Port);
uint32_t power_adc_detect(uint8_t u8Port);
void power_adc_init(void);

#endif

